[tool:pytest]
addopts = --tb=short -v -s --capture=no
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::RuntimeWarning
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning